Description: >

  VPC deployment:
    - 2 public and private subnets across two Availabilty Zones.
    - Internet Gateway, with a default route on the public subnets.
    - 2 NAT Gateways (one in each AZ), and default routes for them in the private subnets.

  ECS cluster deployment:
    - ECS cluster using an AutoScaling Group, with ECS hosts distributed
    across multiple Availability Zones.

  ECS services deployment:
    - ECS services from containers published in ECR or Docker Hub

  Based on https://github.com/aws-samples/ecs-refarch-cloudformation

Resources:
  VPC:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/cf-template-structured/infrastructure/vpc.yaml
      Parameters:
        EnvironmentName: !Ref AWS::StackName
        VpcCIDR: 10.10.0.0/16
        PublicSubnet1CIDR: 10.10.8.0/21
        PublicSubnet2CIDR: 10.10.16.0/21
        PrivateSubnet1CIDR: 10.10.24.0/21
        PrivateSubnet2CIDR: 10.10.32.0/21

  SecurityGroups:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/cf-template-structured/infrastructure/security-groups.yaml
      Parameters:
        EnvironmentName: !Ref AWS::StackName
        VPC: !GetAtt VPC.Outputs.VPC

  ALB:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/cf-template-structured/infrastructure/load-balancers.yaml
      Parameters:
        EnvironmentName: !Ref AWS::StackName
        VPC: !GetAtt VPC.Outputs.VPC
        Subnets: !GetAtt VPC.Outputs.PublicSubnets
        SecurityGroup: !GetAtt SecurityGroups.Outputs.LoadBalancerSecurityGroup

  ECS:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/cf-template-structured/infrastructure/ecs-cluster.yaml
      Parameters:
        EnvironmentName: !Ref AWS::StackName
        InstanceType: t2.small
        ClusterSize: 1
        VPC: !GetAtt VPC.Outputs.VPC
        SecurityGroup: !GetAtt SecurityGroups.Outputs.ECSHostSecurityGroup
        Subnets: !GetAtt VPC.Outputs.PrivateSubnets

  MongoService:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/cf-template-structured/services/reddit-mongo-service.yaml
      Parameters:
        VPC: !GetAtt VPC.Outputs.VPC
        Cluster: !GetAtt ECS.Outputs.Cluster
        DesiredCount: 1
        Listener: !GetAtt ALB.Outputs.Listener
        Path: /mongo

  PostService:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/cf-template-structured/services/reddit-post-service.yaml
      Parameters:
        VPC: !GetAtt VPC.Outputs.VPC
        Cluster: !GetAtt ECS.Outputs.Cluster
        DesiredCount: 1
        PostDatabaseUrl:
          !Join ["/", [!GetAtt ALB.Outputs.LoadBalancerUrl, "mongo"]]
        PostDatabasePort: 80
        Listener: !GetAtt ALB.Outputs.Listener
        Path: /post

  UiService:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/cf-template-structured/services/reddit-ui-service.yaml
      Parameters:
        VPC: !GetAtt VPC.Outputs.VPC
        Cluster: !GetAtt ECS.Outputs.Cluster
        DesiredCount: 1
        PostServiceUrl:
          !Join ["/", [!GetAtt ALB.Outputs.LoadBalancerUrl, "post"]]
        PostServicePort: 80 
        Listener: !GetAtt ALB.Outputs.Listener
        Path: /
        ECSServiceAutoScalingRoleARN: !GetAtt ECS.Outputs.ECSServiceAutoScalingRole

Outputs:
  MongoServiceUrl:
    Description: The URL endpoint for the Reddit Mongo service
    Value: !Join ["/", [!GetAtt ALB.Outputs.LoadBalancerUrl, "mongo"]]

  PostServiceUrl:
    Description: The URL endpoint for the Reddit Post service
    Value: !Join ["/", [!GetAtt ALB.Outputs.LoadBalancerUrl, "post"]]

  UiServiceUrl:
    Description: The URL endpoint for Reddit UI service
    Value: !Join ["", [!GetAtt ALB.Outputs.LoadBalancerUrl, "/"]]
